### ISSUE TITLE
网关服务需要配置

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [maidou2023/chatgpt-mirror-docker#3]
docker-compose中需要配置网关服务，本系统现在正在自建网关，所以还需要调用栋哥的网关：

```yml
CHATPROXY: "https://demo.xyhelper.cn"
# 接入网关的authkey
AUTHKEY: "xyhelper"
```
